_target_: rul_datasets.RulDataModule
reader:
  _target_: rul_datasets.XjtuSyReader
  fd: ???
  norm_rul: True
  truncate_degraded_only: True
batch_size: 128
feature_extractor:
  _target_: rul_adapt.run.utils.XjtuSyExtractor
  window_size: 2560
