# @package _global_

dm:
  source:
    fd: 2
    run_split_dist:
      dev: [1, 7]
      val: [3, 4]
      test: [6]
  target:
    fd: 3
    run_split_dist:
      dev: [1, 2]
      val: []
      test: [3]
  feature_extractor:
    feature_idx: [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 20, 21, 22, 23, 25, 27, 35, 39, 48, 50, 51, 54, 56, 57, 58, 59]