# @package _global_

dm:
  source:
    fd: 3
    run_split_dist:
      dev: [1, 3]
      val: [3]
      test: [2]
    first_time_to_predict: [ 250, 1340, 240 ]
  target:
    fd: 1
    run_split_dist:
      dev: [1, 2]
      val: [3, 4]
      test: [7]
    first_time_to_predict: [ 1200, 140, 1050, 990, 2300, 1480, 1930 ]
  feature_extractor:
    feature_idx: [0, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 20, 21, 22, 23, 25, 27, 38, 41, 46, 48, 50, 56, 57, 58, 59]
