site_name: RUL Adapt
site_url: https://krokotsch.eu/rul-adapt
repo_name: tilman151/rul_adapt
repo_url: https://github.com/tilman151/rul-adapt

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - content.code.annotate

nav:
  - Introduction: index.md
  - API Reference: api/
  - Examples:
      - AdaRUL: examples/adarul.ipynb
      - LSTM-DANN: examples/lstm_dann.ipynb
      - CNN-DANN: examples/cnn_dann.ipynb
      - Conditional: examples/conditional.ipynb
      - Consistency: examples/consistency_dann.ipynb
      - LatentAlign: examples/latent_align.ipynb
      - PseudoLabels: examples/pseudo_labels.ipynb
      - TBiGRU: examples/tbigru.ipynb

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

watch: [rul_adapt]

plugins:
  - search
  - autorefs
  - section-index
  - mkdocs-jupyter:
      no_input: False
  - gen-files:
      scripts: [docs/gen_ref_pages.py]
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://pytorch-lightning.readthedocs.io/en/stable/objects.inv
            - https://torchmetrics.readthedocs.io/en/stable/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://krokotsch.eu/rul-datasets/objects.inv
          options:
            show_source: false