# @package _global_

defaults:
  - approach_base

runner: rul_adapt.run.adarul

dm:
  _target_: rul_datasets.DomainAdaptionDataModule

domain_disc:
  _target_: rul_adapt.model.FullyConnectedHead
  input_channels: ${feature_extractor.fc_units}
  units: [1]
  act_func_on_last_layer: false

pretraining:
  approach:
    _target_: rul_adapt.approach.SupervisedApproach
    lr: ???
    loss_type: rmse

training:
  approach:
      _target_: rul_adapt.approach.AdaRulApproach
      lr: ???
      max_rul: ???
      num_disc_updates: ???
      num_gen_updates: ???
