# @package _global_

defaults:
  - approach_base

runner: rul_adapt.run.dann

dm:
  _target_: rul_datasets.DomainAdaptionDataModule

domain_disc:
  _target_: rul_adapt.model.FullyConnectedHead
  input_channels: ${feature_extractor.fc_units}
  units: ???
  act_func_on_last_layer: false

pretraining:
  approach:
    _target_: rul_adapt.approach.SupervisedApproach
    lr: ???
    loss_type: rmse

training:
  approach:
      _target_: rul_adapt.approach.ConsistencyApproach
      lr: ???
      consistency_factor: ???
      max_epochs: ${training.trainer.max_epochs}
      loss_type: rmse
