# @package _global_

defaults:
  - approach_base

runner: rul_adapt.run.mmd

dm:
  _target_: rul_datasets.LatentAlignDataModule

training:
  approach:
      _target_: rul_adapt.approach.LatentAlignApproach
      lr: ???
      alpha_healthy: ???
      alpha_direction: ???
      alpha_level: ???
      alpha_fusion: ???
      loss_type: rmse
