domain_disc:
  units: ['${regressor.input_channels}', '${regressor.input_channels}', 1]

pretraining:
  approach:
    rul_scale: 125

training:
  approach:
      lr: 0.00014
      max_rul: 125
      num_disc_updates: 20
      num_gen_updates: 7
