defaults:
  - _self_
  - ../fuzzy_sets@training.approach

domain_disc:
  units: ["${regressor.input_channels}", "${regressor.input_channels}", 1]

training:
  approach:
      lr: 6e-5
      dann_factor: 2.6
      dynamic_adaptive_factor: 0.5
      fuzzy_sets: ???
