defaults:
  - _self_
  - ../fuzzy_sets@training.approach

training:
  approach:
      lr: 0.00042
      mmd_factor: 0.4
      num_mmd_kernels: 2
      dynamic_adaptive_factor: 0.3
      fuzzy_sets: ???
