defaults:
  - _self_
  - ../fuzzy_sets@training.approach

domain_disc:
  units: ["${regressor.input_channels}", "${regressor.input_channels}", 1]

training:
  approach:
      lr: 1e-5
      dann_factor: 5.7
      dynamic_adaptive_factor: 0.3
      fuzzy_sets: ???
