defaults:
  - _self_
  - ../fuzzy_sets@training.approach

domain_disc:
  units: ["${regressor.input_channels}", 1]

training:
  approach:
      lr: 0.00015
      dann_factor: 0.3
      dynamic_adaptive_factor: 0.2
      fuzzy_sets: ???
