defaults:
  - _self_
  - ../fuzzy_sets@training.approach

training:
  approach:
      lr: 0.00087
      mmd_factor: 0.1
      num_mmd_kernels: 4
      dynamic_adaptive_factor: 0.7
      fuzzy_sets: ???
