defaults:
  - _self_
  - ../fuzzy_sets@training.approach

training:
  approach:
      lr: 0.001
      mmd_factor: 1.0
      num_mmd_kernels: 5
      dynamic_adaptive_factor: 0.5
      fuzzy_sets: ???
