defaults:
  - _self_
  - ../fuzzy_sets@training.approach

domain_disc:
  units: [1]

training:
  approach:
      lr: 0.001
      dann_factor: 1.0
      dynamic_adaptive_factor: 0.5
      fuzzy_sets: ???
