defaults:
  - _self_
  - ../fuzzy_sets@training.approach

training:
  approach:
      lr: 0.0009
      mmd_factor: 0.9
      num_mmd_kernels: 3
      dynamic_adaptive_factor: 0.5
      fuzzy_sets: ???
