# @package _global_

dm:
  source:
    _target_: rul_datasets.XjtuSyReader
    window_size: null
    run_split_dist:
      dev: [1, 2, 3, 4, 5]
      val: []
      test: []
    norm_rul: True
  target:
    percent_broken: 0.5
    truncate_degraded_only: True
    norm_rul: True
  kwargs:
    feature_extractor:
      _target_: rul_adapt.approach.latent_align.ChunkWindowExtractor
      window_size: 5
      chunk_size: 256
  adaption_kwargs:
    split_by_max_rul: True

feature_extractor:
  input_channels: 2
  seq_len: 1280  # window_size * chunk_size