name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    needs: [lint]
    uses: ./.github/workflows/test.yaml
