name: Test
on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-poetry
        with:
          poetry-version: "1.2.2"
      - run: poetry run pytest tests
